#!/usr/bin/env python

from __future__ import division
import rospy

from jsk_20160505_test_message_filters.msg import StringStamped


def callback(event):
    msg.header.stamp = rospy.Time.now()
    pub.publish(msg)


rospy.init_node('publish_string')
rate = rospy.get_param('~rate', 10)
timer = rospy.Timer(rospy.Duration(1 / rate), callback)
pub = rospy.Publisher('~', StringStamped, queue_size=1)
msg = StringStamped()
msg.header.frame_id = 'publish_string'
msg.header.stamp = rospy.Time.now()
msg.data = 'data'
rospy.spin()
